sensors:
    oakd_front:
        type: 0 # 0 = pos_3d measurement. see Sensors::SensorType in obs_models.hpp
        topic: "yolov4_publisher/color/yolov4_Spatial_detections"
        sigma: [34.0059364,25.9475303,54.9710593] ### Everything from this line onward gets calibrated
        p_d: 0.98
        q_d: 0.02

        meas_labels: ["null", "person"] # The types of measurements you get from this sensor

        class_meas_probability: # The types of objects you want to track
            # Measurement probabilities
            null: [0.95, 0.05] # p(z=null|x=null), p(z=person|x=null) / true neg, false pos. Calibrate in empty room.
            person: [0.1, 0.9] # p(z=null|x=person), p(z=person|x=person) / false neg, true pos. Calibrate with object in view. 
        
    # sick_lidar:
    #     type: "pos_2d"
    #     topic: "scan"
    #     sigma: [34.0059364,25.9475303,0]
    #     p_d: 0.98
    #     q_d: 0.02

    #     meas_labels: ["null", "leg"] # The types of measurements you get from this sensor

    #     class_labels:
    #         person:
    #             meas_labels:    ["null", "leg"]
    #             meas_probabilities: [0.1, 0.9] 
            
    #         furniture:
    #             meas_labels:    ["null", "leg"]
    #             meas_probabilities: [0.1, 0.9]               

    #         null:
    #             meas_labels:    ["null", "leg"]
    #             meas_probabilities: [0.9, 0.1]


    # Some notes for the calibration process:
    # - class_meas_probability should be the same number of entries for each sensor, even if sensor can't detect the class.
    # - i.e. should run the calibration for each class of interest, and record what all the sensors see.