transition:
    standing: #activity label/name
        type: 0 # constant position
        sigma: [13.5688255, 9.80265414, 39.5476227,  0., 0., 0.]
        mode_trans: [.6, .4] # probability person will remain standing (0.6), or start moving (0.4)
    walking: #activity label/name
        type: 1 # constant velocity
        sigma: [135.688255, 98.0265414, 395.476227, 1.00000196, 0.999837353, 0.997463441]
        mode_trans: [.4, .6] # probability person will stand (0.4), or remain moving (0.6)